#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GoDough.Resource", IsApplication=true)]

namespace GoDough
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f040001
			public const int currencies = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int spending_categories = 2130968576;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060003
			public const int Add = 2131099651;
			
			// aapt resource value: 0x7f060007
			public const int BalLeft = 2131099655;
			
			// aapt resource value: 0x7f060004
			public const int Delete = 2131099652;
			
			// aapt resource value: 0x7f06000d
			public const int balNumber = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int button1 = 2131099663;
			
			// aapt resource value: 0x7f060011
			public const int editText1 = 2131099665;
			
			// aapt resource value: 0x7f060005
			public const int edittext = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int linearLayout1 = 2131099650;
			
			// aapt resource value: 0x7f06000b
			public const int linearLayout2 = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int linearLayout3 = 2131099660;
			
			// aapt resource value: 0x7f06000e
			public const int linearLayout4 = 2131099662;
			
			// aapt resource value: 0x7f060012
			public const int pastTrans = 2131099666;
			
			// aapt resource value: 0x7f060006
			public const int plotView1 = 2131099654;
			
			// aapt resource value: 0x7f060010
			public const int plot_view = 2131099664;
			
			// aapt resource value: 0x7f060001
			public const int spinner1 = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int textView1 = 2131099648;
			
			// aapt resource value: 0x7f060008
			public const int toGategory = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int toGraph = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int toTransactions = 2131099658;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int categoriesLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Category = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Graph = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Transactions = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
